### ISSUE TITLE
Should not require FodyDependencyInjection at runtime

### ISSUE THREAD

**Issue by SimonCropp** [jorgehmv/FodyDependencyInjection#1]
Usages and references to FodyDependencyInjection should be removed at compile time so FodyDependencyInjection.dll does not need to be deployed

**Comment by jorgehmv** [comment]
I don't see a way to achieve this since there needs to be a reference to the current container, currently this is done by class ConfigurableInjection inside Fody.DependencyInjection.dll. The reference is needed to configure instances inside <>__EnsureConfiguration method.

Any ideas?

**Comment by SimonCropp** [comment]
before i answer this... what do you use `ConfigurableInjection.Container` for

**Comment by jorgehmv** [comment]
It keeps a reference of the IoC container, this is needed to configure an instance on creation. The <>__EnsureConfiguration method uses this instance to call the appropriate framework method to configure the instance (different for each IoC).

**Comment by SimonCropp** [comment]
Does `ConfigurableInjection.Container` need to be static across multiple assemblies?

**Comment by jorgehmv** [comment]
definitely, usually a single IoC configuration is used for the entire application.

**Comment by SimonCropp** [comment]
in that case ignore this issue
